include:
  - package:flutter_lints/flutter.yaml
  - package:very_good_analysis/analysis_options.yaml





analyzer:
  exclude: [lib/**.g.dart, lib/**.freezed.dart] 
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    todo: ignore

